# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sentinel_pb2 as sentinel__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sentinel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorServiceStub(object):
    """The core management service for the planetary analysis mesh.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/sentinel.v1.OrchestratorService/RegisterNode',
                request_serializer=sentinel__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=sentinel__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.SubmitScan = channel.unary_unary(
                '/sentinel.v1.OrchestratorService/SubmitScan',
                request_serializer=sentinel__pb2.SubmitScanRequest.SerializeToString,
                response_deserializer=sentinel__pb2.SubmitScanResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.unary_stream(
                '/sentinel.v1.OrchestratorService/StreamTelemetry',
                request_serializer=sentinel__pb2.StreamTelemetryRequest.SerializeToString,
                response_deserializer=sentinel__pb2.TelemetryUpdate.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """The core management service for the planetary analysis mesh.
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=sentinel__pb2.RegisterNodeRequest.FromString,
                    response_serializer=sentinel__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'SubmitScan': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitScan,
                    request_deserializer=sentinel__pb2.SubmitScanRequest.FromString,
                    response_serializer=sentinel__pb2.SubmitScanResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=sentinel__pb2.StreamTelemetryRequest.FromString,
                    response_serializer=sentinel__pb2.TelemetryUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.v1.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.v1.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """The core management service for the planetary analysis mesh.
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.v1.OrchestratorService/RegisterNode',
            sentinel__pb2.RegisterNodeRequest.SerializeToString,
            sentinel__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.v1.OrchestratorService/SubmitScan',
            sentinel__pb2.SubmitScanRequest.SerializeToString,
            sentinel__pb2.SubmitScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sentinel.v1.OrchestratorService/StreamTelemetry',
            sentinel__pb2.StreamTelemetryRequest.SerializeToString,
            sentinel__pb2.TelemetryUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConsensusServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/sentinel.v1.ConsensusService/RequestVote',
                request_serializer=sentinel__pb2.VoteRequest.SerializeToString,
                response_deserializer=sentinel__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/sentinel.v1.ConsensusService/AppendEntries',
                request_serializer=sentinel__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=sentinel__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)


class ConsensusServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=sentinel__pb2.VoteRequest.FromString,
                    response_serializer=sentinel__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=sentinel__pb2.AppendEntriesRequest.FromString,
                    response_serializer=sentinel__pb2.AppendEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.v1.ConsensusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.v1.ConsensusService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsensusService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.v1.ConsensusService/RequestVote',
            sentinel__pb2.VoteRequest.SerializeToString,
            sentinel__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.v1.ConsensusService/AppendEntries',
            sentinel__pb2.AppendEntriesRequest.SerializeToString,
            sentinel__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class InferenceServiceStub(object):
    """Inference Service for AI-driven code analysis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InferLogic = channel.unary_unary(
                '/sentinel.v1.InferenceService/InferLogic',
                request_serializer=sentinel__pb2.InferenceRequest.SerializeToString,
                response_deserializer=sentinel__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.AnalyzeVulnerability = channel.unary_unary(
                '/sentinel.v1.InferenceService/AnalyzeVulnerability',
                request_serializer=sentinel__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=sentinel__pb2.AnalysisResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Inference Service for AI-driven code analysis
    """

    def InferLogic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeVulnerability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InferLogic': grpc.unary_unary_rpc_method_handler(
                    servicer.InferLogic,
                    request_deserializer=sentinel__pb2.InferenceRequest.FromString,
                    response_serializer=sentinel__pb2.InferenceResponse.SerializeToString,
            ),
            'AnalyzeVulnerability': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeVulnerability,
                    request_deserializer=sentinel__pb2.AnalysisRequest.FromString,
                    response_serializer=sentinel__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentinel.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentinel.v1.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Inference Service for AI-driven code analysis
    """

    @staticmethod
    def InferLogic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.v1.InferenceService/InferLogic',
            sentinel__pb2.InferenceRequest.SerializeToString,
            sentinel__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeVulnerability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentinel.v1.InferenceService/AnalyzeVulnerability',
            sentinel__pb2.AnalysisRequest.SerializeToString,
            sentinel__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
